server:
  port: 9191
spring:
  application:
    name: awesomesentinel
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:c:/h2/mydb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    platform: h2
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update # 更新策略
  h2: # 控制台
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
